# Generated by Django 5.1.2 on 2024-10-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassengerApi', '0002_passenger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
