# Generated by Django 5.1.2 on 2024-10-28 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DriverApi', '0001_initial'),
        ('PassengerApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentbooking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PassengerApi.passenger'),
        ),
        migrations.AddField(
            model_name='currentbooking',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriverApi.driver'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriverApi.driver'),
        ),
        migrations.AddField(
            model_name='driverrideshistory',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriverApi.driver'),
        ),
        migrations.AddField(
            model_name='driverrideshistory',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PassengerApi.passenger'),
        ),
    ]
