# Generated by Django 5.1.2 on 2024-10-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverApi', '0005_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbooking',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
