# Generated by Django 5.1.2 on 2024-10-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverApi', '0006_alter_currentbooking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
